COLUMNS :
  City : object
  area : int64 
  rooms : int64 
  bathrooms : int64 
  parking Space : int64 
  floor : int64 
  pets : object
  furnished : object
  Homeowners Association : int64 
  rent_amount    : int64 
  property_tax   : int64 
  fire_insurance : int64 

TARGET_COLUMN:
  total_amount   : int64